### ISSUE TITLE
Code fence syntax

### ISSUE THREAD

**Issue by mattwiebe** [evansolomon/wp-github-flavored-markdown-comments#1]
Markdown Extra uses tildes instead of backticks for [fenced code blocks](http://michelf.ca/projects/php-markdown/extra/#fenced-code-blocks). It doesn't appear to be configurable, alas.

**Comment by evansolomon** [comment]
I do have backtick-fenced code blocks in this plugin ([source](https://github.com/evansolomon/wp-github-flavored-markdown-comments/blob/70470794626ccf34f8a2cc3c62526d3c0f4aa0a4/github-flavored-markdown-comments.php#L37)).  Is there something else you think should be added?

I haven't added syntax highlighting support yet, but I'm planning to do that at some point.  The backtick syntax does currently allow a language param, like Github, but doesn't currently do anything with it.

**Comment by mattwiebe** [comment]
My bad - didn't see your overload there.

**Comment by evansolomon** [comment]
Cool. I would still like to add syntax highlighting if the server has Pygments installed, but I haven't gotten to that yet.

Going to close this one since it's resolved-ish.
