### ISSUE TITLE
Not so much an issue as a feature request.

### ISSUE THREAD

**Issue by tjfwalker** [evansolomon/wp-github-flavored-markdown-comments#2]
It'd be nice if this did Markdown for posts too, like http://wordpress.org/extend/plugins/wp-markdown/ but in delicious Gitgub flavor.

Thanks for considering it.

**Comment by evansolomon** [comment]
I use Mark Jaquith's [Markdown on Save](https://github.com/markjaquith/markdown-on-save), which I highly recommend. It is missing a couple of the GitHub-added features, but we actually use the same Markdown library. It would make more sense for Mark to add it to his plugin (or fork it) than to add Markdown in posts to this plugin.
