### ISSUE TITLE
found fatal error on actvate

### ISSUE THREAD

**Issue by krissanawat** [evansolomon/wp-github-flavored-markdown-comments#3]
Parse error: syntax error, unexpected T_FUNCTION in /home/taqmageq/public_html/wp-content/plugins/github-flavored-markdown-comments/github-flavored-markdown-comments.php on line 13

**Comment by evansolomon** [comment]
Are you using PHP 5.3+?  WordPress works on PHP 5.2.something, but this plugin requires at least 5.3.  The error you're getting sounds like your version of PHP doesn't support [closures](http://php.net/manual/en/functions.anonymous.php), which were added in PHP 5.3.

See [this section](https://github.com/evansolomon/wp-github-flavored-markdown-comments#dragons) in the Readme.
