### ISSUE TITLE
How can you embed external markdown?

### ISSUE THREAD

**Issue by shovanco** [evansolomon/wp-github-flavored-markdown-comments#4]
Hi

Is there a way you can embed external markdown inside the page? 
eg: https://raw.githubusercontent.com/makotokw/wp-gfm/master/README.md

Thanks

**Comment by evansolomon** [comment]
I'm not sure what external markdown means (and I can't tell from that readme link). Can you give me a clearer example of what you mean?

**Comment by tfrommen** [comment]
@evansolomon citing from the linked file:

----

#### Embed content

Supported embed markdown file by ``[embed_markdown]`` shortcode.

```
[embed_markdown url="https://raw.githubusercontent.com/makotokw/wp-gfm/master/README.md"]
```

----

It's about parsing some remote file, and then displaying its contents.

**Comment by shovanco** [comment]
Thanks
